name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Boost
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev

      - name: Install Google Test
        run: |
          sudo apt-get install -y libgtest-dev
          sudo apt-get install -y cmake
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp *.a /usr/lib

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: |
          ctest -C ${{env.BUILD_TYPE}}
          ./test/LoggerTest

      - name: Install Google Benchmark
        run: |
          sudo apt-get install -y libbenchmark-dev
    
      - name: Benchmark
        working-directory: ${{github.workspace}}/build
        run: |
          ./cpp_logger

